begin;
select plan(40);
select has_schema('public','public schema');
select has_table('public','profiles','profiles');
select has_table('public','organizations','organizations');
select has_table('public','organization_users','organization_users');
select has_table('public','units_of_measure','units');
select has_table('public','products','products');
select has_table('public','contacts','contacts');
select has_table('public','number_sequences','number_sequences');
select has_table('public','accounts','accounts');
select has_table('public','journal_entries','journals');
select has_table('public','account_transactions','journal lines');
select has_table('public','accounting_periods','periods');
select has_table('public','purchase_invoices','purchase invoices');
select has_table('public','purchase_items','purchase items');
select has_table('public','sales_invoices','sales invoices');
select has_table('public','sales_items','sales items');
select has_table('public','inventory_balances','inventory balances');
select has_table('public','inventory_transactions','inventory ledger');
select has_table('public','expense_categories','expense categories');
select has_table('public','expenses','expenses');
select has_table('public','payments','payments');
select has_table('public','payment_allocations','allocations');
select has_function('private','is_org_member',ARRAY['uuid']);
select has_function('private','has_org_role',ARRAY['uuid','text[]']);
select col_not_null('public.purchase_items','discount_per_unit','purchase discount allocation');
select col_not_null('public.purchase_items','net_unit_cost','purchase net cost');
select col_not_null('public.sales_items','discount_per_unit','sales discount allocation');
select col_not_null('public.sales_items','net_unit_price','sales net price');
select has_index('public','organization_users_one_owner_uq','one active owner');
select has_index('public','accounting_periods_no_overlap_excl','no overlapping periods');
select has_index('public','products_product_code_key','product code unique');
select has_index('public','accounts_account_code_key','account code unique');
select has_index('public','purchase_invoices_invoice_number_key','purchase number unique');
select has_index('public','sales_invoices_invoice_number_key','sales number unique');
select has_trigger('public','organizations','organizations_bootstrap_owner_trg','owner bootstrap');
select has_trigger('public','journal_entries','journal_entries_post_trg','journal posting validation');
select has_trigger('public','account_transactions','account_transactions_immutable_trg','journal line immutability');
select has_trigger('public','inventory_transactions','inventory_transactions_immutable_trg','inventory immutability');
select has_trigger('public','payment_allocations','payment_allocations_validation_trg','allocation validation');
select * from finish();
rollback;