begin;
create extension if not exists pgtap with schema extensions;
select plan(61);
select has_schema('public','public schema');
select has_table('public','profiles','profiles');
select has_table('public','organizations','organizations');
select has_table('public','organization_users','organization_users');
select has_table('public','units_of_measure','units');
select has_table('public','products','products');
select has_table('public','contacts','contacts');
select has_table('public','number_sequences','number_sequences');
select has_table('public','accounts','accounts');
select has_table('public','journal_entries','journals');
select has_table('public','account_transactions','journal lines');
select has_table('public','accounting_periods','periods');
select has_table('public','purchase_invoices','purchase invoices');
select has_table('public','purchase_items','purchase items');
select has_table('public','sales_invoices','sales invoices');
select has_table('public','sales_items','sales items');
select has_table('public','inventory_balances','inventory balances');
select has_table('public','inventory_transactions','inventory ledger');
select has_table('public','expense_categories','expense categories');
select has_table('public','expenses','expenses');
select has_table('public','payments','payments');
select has_table('public','payment_allocations','allocations');
select has_function('private','is_org_member',ARRAY['uuid']);
select has_function('private','has_org_role',ARRAY['uuid','text[]']);
select has_function('private','validate_journal_post',ARRAY[]::text[],'journal posting validator');
select has_function('private','validate_purchase_post',ARRAY[]::text[],'purchase posting validator');
select has_function('private','validate_sale_post',ARRAY[]::text[],'sales posting validator');
select has_function('public','post_purchase_invoice',ARRAY['uuid','uuid'],'purchase posting RPC');
select has_function('public','post_sales_invoice',ARRAY['uuid','uuid'],'sales posting RPC');
select has_function('public','post_expense',ARRAY['uuid','uuid'],'expense posting RPC');
select has_function('public','post_payment',ARRAY['uuid','uuid','jsonb'],'payment posting RPC');
select has_function('public','post_manual_journal',ARRAY['uuid','date','text','jsonb','text'],'manual journal RPC');
select has_function('public','reverse_journal',ARRAY['uuid','date','text'],'reversal RPC');
select col_not_null('public.purchase_items','discount_per_unit','purchase discount allocation');
select col_not_null('public.purchase_items','net_unit_cost','purchase net cost');
select col_not_null('public.sales_items','discount_per_unit','sales discount allocation');
select col_not_null('public.sales_items','net_unit_price','sales net price');
select col_type_is('public.purchase_items','unit_cost','numeric','purchase unit cost precision');
select col_type_is('public.sales_items','unit_price','numeric','sales unit price precision');
select col_type_is('public.purchase_invoices','payable_account_id','uuid','purchase payable account');
select col_type_is('public.sales_invoices','receivable_account_id','uuid','sales receivable account');
select col_type_is('public.expenses','payable_account_id','uuid','expense payable account');
select col_type_is('public.payments','settlement_account_id','uuid','payment settlement account');
select has_index('public','organization_users_one_owner_uq','one active owner');
select has_index('public','accounting_periods_no_overlap_excl','no overlapping periods');
select has_index('public','products_organization_id_product_code_key','product code unique');
select has_index('public','journal_entries_one_reversal_uq','one reversal per journal');
select has_index('public','accounts_organization_id_account_code_key','account code unique');
select has_index('public','purchase_invoices_organization_id_invoice_number_key','purchase number unique');
select has_index('public','sales_invoices_organization_id_invoice_number_key','sales number unique');
select has_trigger('public','organizations','organizations_bootstrap_owner_trg','owner bootstrap');
select has_trigger('public','journal_entries','journal_entries_post_trg','journal posting validation');
select has_trigger('public','account_transactions','account_transactions_immutable_trg','journal line immutability');
select has_trigger('public','inventory_transactions','inventory_transactions_immutable_trg','inventory immutability');
select has_trigger('public','payment_allocations','payment_allocations_validation_trg','allocation validation');
select has_trigger('public','products','products_tenant_guard_trg','tenant move guard');
select has_trigger('public','purchase_invoices','purchase_invoices_immutable_trg','purchase document guard');
select has_trigger('public','sales_invoices','sales_invoices_immutable_trg','sales document guard');
select has_trigger('public','payments','payments_immutable_trg','payment document guard');
select has_trigger('public','expenses','expenses_immutable_trg','expense document guard');
select has_trigger('public','payment_allocations','payment_allocations_immutable_trg','allocation immutability');
select * from finish();
rollback;