begin;
create extension if not exists pgtap with schema extensions;
select plan(62);
select has_schema('public','public schema');
select has_table('public','profiles','profiles');
select has_table('public','organizations','organizations');
select has_table('public','organization_users','organization_users');
select has_table('public','units_of_measure','units');
select has_table('public','products','products');
select has_table('public','contacts','contacts');
select has_table('public','number_sequences','number_sequences');
select has_table('public','accounts','accounts');
select has_table('public','journal_entries','journals');
select has_table('public','account_transactions','journal lines');
select has_table('public','accounting_periods','periods');
select has_table('public','purchase_invoices','purchase invoices');
select has_table('public','purchase_items','purchase items');
select has_table('public','sales_invoices','sales invoices');
select has_table('public','sales_items','sales items');
select has_table('public','inventory_balances','inventory balances');
select has_table('public','inventory_transactions','inventory ledger');
select has_table('public','expense_categories','expense categories');
select has_table('public','expenses','expenses');
select has_table('public','payments','payments');
select has_table('public','payment_allocations','allocations');
select is(
  (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'),
  21::bigint,
  'exactly 21 public ERP tables exist'
);
select has_function('private','is_org_member',ARRAY['uuid']);
select has_function('private','has_org_role',ARRAY['uuid','text[]']);
select has_function('private','validate_journal_post',ARRAY[]::text[],'journal posting validator');
select has_function('private','validate_purchase_post',ARRAY[]::text[],'purchase posting validator');
select has_function('private','validate_sale_post',ARRAY[]::text[],'sales posting validator');
select has_function('public','post_purchase_invoice',ARRAY['uuid','uuid'],'purchase posting RPC');
select has_function('public','post_sales_invoice',ARRAY['uuid','uuid'],'sales posting RPC');
select has_function('public','post_expense',ARRAY['uuid','uuid'],'expense posting RPC');
select has_function('public','post_payment',ARRAY['uuid','uuid','jsonb'],'payment posting RPC');
select has_function('public','post_manual_journal',ARRAY['uuid','date','text','jsonb','text'],'manual journal RPC');
select has_function('public','reverse_journal',ARRAY['uuid','date','text'],'reversal RPC');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='purchase_items' and column_name='discount_per_unit' and is_nullable='NO'),'purchase discount allocation');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='purchase_items' and column_name='net_unit_cost' and is_nullable='NO'),'purchase net cost');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='sales_items' and column_name='discount_per_unit' and is_nullable='NO'),'sales discount allocation');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='sales_items' and column_name='net_unit_price' and is_nullable='NO'),'sales net price');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='purchase_items' and column_name='unit_cost' and data_type='numeric'),'purchase unit cost precision');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='sales_items' and column_name='unit_price' and data_type='numeric'),'sales unit price precision');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='purchase_invoices' and column_name='payable_account_id' and data_type='uuid'),'purchase payable account');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='sales_invoices' and column_name='receivable_account_id' and data_type='uuid'),'sales receivable account');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='expenses' and column_name='payable_account_id' and data_type='uuid'),'expense payable account');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='payments' and column_name='settlement_account_id' and data_type='uuid'),'payment settlement account');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='organization_users_one_owner_uq'),'one active owner');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='accounting_periods_no_overlap_excl'),'no overlapping periods');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='products_organization_id_product_code_key'),'product code unique');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='journal_entries_one_reversal_uq'),'one reversal per journal');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='accounts_organization_id_account_code_key'),'account code unique');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='purchase_invoices_organization_id_invoice_number_key'),'purchase number unique');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='sales_invoices_organization_id_invoice_number_key'),'sales number unique');
select has_trigger('public','organizations','organizations_bootstrap_owner_trg','owner bootstrap');
select has_trigger('public','journal_entries','journal_entries_post_trg','journal posting validation');
select has_trigger('public','account_transactions','account_transactions_immutable_trg','journal line immutability');
select has_trigger('public','inventory_transactions','inventory_transactions_immutable_trg','inventory immutability');
select has_trigger('public','payment_allocations','payment_allocations_validation_trg','allocation validation');
select has_trigger('public','products','products_tenant_guard_trg','tenant move guard');
select has_trigger('public','purchase_invoices','purchase_invoices_immutable_trg','purchase document guard');
select has_trigger('public','sales_invoices','sales_invoices_immutable_trg','sales document guard');
select has_trigger('public','payments','payments_immutable_trg','payment document guard');
select has_trigger('public','expenses','expenses_immutable_trg','expense document guard');
select has_trigger('public','payment_allocations','payment_allocations_immutable_trg','allocation immutability');
select * from finish();
rollback;