import Link from "next/link";
import { notFound } from "next/navigation";
import { ConfigurationManager, type ConfigField } from "@/components/configuration-manager";
import { getCurrentOrganization } from "@/lib/supabase/organization";
import { createClient } from "@/lib/supabase/server";
import { saveAccount, saveExpenseCategory, savePeriod, saveUnit, toggleAccount, toggleExpenseCategory, togglePeriod, toggleUnit } from "@/app/configuration/actions";

const configs = {
  inventory: { units: { title: "Units of Measure", description: "Manage the reusable units assigned to products.", href: "/inventory/configuration/units" } },
  accounting: {
    accounts: { title: "Chart of Accounts", description: "Manage postable and control accounts used by ERP posting.", href: "/accounting/configuration/accounts" },
    periods: { title: "Accounting Periods", description: "Create and open/close accounting periods used by posting controls.", href: "/accounting/configuration/periods" },
    sequences: { title: "Number Sequences", description: "Review the automatic numbering configuration generated by the existing database.", href: "/accounting/configuration/sequences" },
  },
  expenses: { categories: { title: "Expense Categories", description: "Classify expenses and map each category to an expense account.", href: "/expenses/configuration/categories" } },
} as const;

type Module = keyof typeof configs;

export default async function ModuleConfigurationPage({ params, searchParams }: {
  params: Promise<{ module: string; setting: string }>;
  searchParams: Promise<{ edit?: string }>;
}) {
  const { module, setting } = await params;
  const query = await searchParams;
  if (!(module in configs) || !(setting in configs[module as Module])) notFound();

  const org = await getCurrentOrganization();
  const supabase = await createClient();
  const user = (await supabase.auth.getUser()).data.user;
  if (!user) return null;

  const config = (configs[module as Module] as Record<string, { title: string; description: string; href: string }>)[setting];
  let rows: Record<string, unknown>[] = [];
  let editingRow: Record<string, unknown> | undefined;
  let fields: ConfigField[] = [];
  let action: any;
  let toggleAction: any;
  let readOnly = false;

  if (module === "inventory" && setting === "units") {
    const { data } = await supabase.from("units_of_measure").select("id,name,is_active,created_at").eq("organization_id", org.id).order("name");
    rows = data ?? [];
    fields = [{ name: "name", label: "Unit name", required: true, placeholder: "e.g. Piece" }, { name: "is_active", label: "Active", type: "checkbox" }];
    action = saveUnit; toggleAction = toggleUnit;
  }

  if (module === "accounting" && setting === "accounts") {
    const { data } = await supabase.from("accounts").select("id,account_code,account_name,account_type,parent_account_id,normal_balance,is_control_account,is_system_account,is_postable,is_active").eq("organization_id", org.id).order("account_code");
    rows = data ?? [];
    fields = [
      { name: "account_code", label: "Account code", required: true },
      { name: "account_name", label: "Account name", required: true },
      { name: "account_type", label: "Type", type: "select", required: true, options: ["asset","liability","equity","revenue","expense"].map(v => ({ value: v, label: v[0].toUpperCase() + v.slice(1) })) },
      { name: "normal_balance", label: "Normal balance", type: "select", required: true, options: [{ value: "debit", label: "Debit" }, { value: "credit", label: "Credit" }] },
      { name: "parent_account_id", label: "Parent account", type: "select", options: rows.map(r => ({ value: String(r.id), label: String(r.account_code) + " — " + String(r.account_name) })) },
      { name: "is_control_account", label: "Control account", type: "checkbox" },
      { name: "is_postable", label: "Postable", type: "checkbox" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ];
    action = saveAccount; toggleAction = toggleAccount;
  }

  if (module === "accounting" && setting === "periods") {
    const { data } = await supabase.from("accounting_periods").select("id,name,start_date,end_date,status,closed_at").eq("organization_id", org.id).order("start_date", { ascending: false });
    rows = data ?? [];
    fields = [
      { name: "name", label: "Period name", required: true, placeholder: "e.g. October 2026" },
      { name: "start_date", label: "Start date", type: "date", required: true },
      { name: "end_date", label: "End date", type: "date", required: true },
    ];
    action = savePeriod; toggleAction = togglePeriod;
  }

  if (module === "accounting" && setting === "sequences") {
    const { data } = await supabase.from("number_sequences").select("id,document_type,prefix,next_number,padding,is_active").eq("organization_id", org.id).order("document_type");
    rows = data ?? [];
    fields = [
      { name: "document_type", label: "Document type" },
      { name: "prefix", label: "Prefix" },
      { name: "next_number", label: "Next number" },
      { name: "padding", label: "Padding" },
    ];
    readOnly = true;
  }

  if (module === "expenses" && setting === "categories") {
    const [{ data: categories }, { data: accounts }] = await Promise.all([
      supabase.from("expense_categories").select("id,category_code,name,expense_account_id,is_active").eq("organization_id", org.id).order("name"),
      supabase.from("accounts").select("id,account_code,account_name").eq("organization_id", org.id).eq("is_active", true).order("account_code"),
    ]);
    rows = categories ?? [];
    fields = [
      { name: "category_code", label: "Category code", required: true },
      { name: "name", label: "Category name", required: true },
      { name: "expense_account_id", label: "Expense account", type: "select", required: true, options: (accounts ?? []).map(a => ({ value: a.id, label: a.account_code + " — " + a.account_name })) },
      { name: "is_active", label: "Active", type: "checkbox" },
    ];
    action = saveExpenseCategory; toggleAction = toggleExpenseCategory;
  }

  editingRow = query.edit ? rows.find(row => String(row.id) === query.edit) : undefined;

  const backHref = module === "inventory" ? "/inventory" : module === "accounting" ? "/accounting" : "/expenses";

  return (
      <div className="settings-page">
        <div className="page-heading">
          <div className="page-heading-copy">
            <p className="eyebrow">{module} configuration</p>
            <h1>{config.title}</h1>
            <p>{config.description}</p>
          </div>
          <Link className="secondary-button compact" href={backHref}>Back to module</Link>
        </div>
        <ConfigurationManager
          title={config.title}
          description={config.description}
          action={action}
          toggleAction={toggleAction}
          fields={fields}
          rows={rows}
          editingRow={editingRow}
          editHref={config.href}
          newHref={config.href}
          emptyText={"No " + config.title.toLowerCase() + " configured yet."}
          readOnly={readOnly}
        />
      </div>
  );
}
