import { ErpPageShell } from "@/components/erp-page-shell";
import { DataTable, DataTableEmpty } from "@/components/data-table";
import { OpeningStockForm } from "@/components/inventory-opening-stock-form";
import { InventoryAdjustmentForm } from "@/components/inventory-adjustment-form";
import { getCurrentOrganization } from "@/lib/supabase/organization";
import { createClient } from "@/lib/supabase/server";
import { postInventoryAdjustment } from "./adjustment-action";

export default async function InventoryPage(){
 const org=await getCurrentOrganization(),supabase=await createClient();
 const [{data:balances,error},{data:tx},{data:openingJournals},{data:activeProducts},{data:accounts}]=await Promise.all([
  supabase.from("inventory_balances").select("id,product_id,quantity,average_cost,inventory_value,updated_at").eq("organization_id",org.id).order("updated_at",{ascending:false}),
  supabase.from("inventory_transactions").select("id,transaction_number,product_id,transaction_date,transaction_type,direction,quantity,unit_cost,total_value,reference_type,reference_id,unit_cost_before,average_cost_after,created_at").eq("organization_id",org.id).order("transaction_date",{ascending:false}).limit(500),
  supabase.from("journal_entries").select("id,entry_number,entry_date,status,entry_type").eq("organization_id",org.id).eq("entry_type","opening").eq("status","posted").order("entry_date",{ascending:false}),
  supabase.from("products").select("id,product_code,name").eq("organization_id",org.id).eq("is_active",true).order("product_code"),
  supabase.from("accounts").select("id,account_code,account_name,account_type").eq("organization_id",org.id).eq("is_active",true).eq("is_postable",true).order("account_code")
 ]);
 const productIds=[...new Set((balances??[]).map(x=>x.product_id).concat((tx??[]).map(x=>x.product_id)))];
 const {data:stockProducts}=productIds.length?await supabase.from("products").select("id,product_code,name").eq("organization_id",org.id).in("id",productIds):{data:[]};
 const product=(id:string)=>stockProducts?.find(x=>x.id===id)||activeProducts?.find(x=>x.id===id);
 const totalQty=(balances??[]).reduce((a,x)=>a+Number(x.quantity),0);
 const totalValue=(balances??[]).reduce((a,x)=>a+Number(x.inventory_value),0);
 const canAdjust=["owner","admin","manager"].includes(org.role);
 return <ErpPageShell><div className="module-page">
 <div className="page-heading"><div><p className="eyebrow">Operations</p><h1>Inventory</h1><p>Opening stock, controlled adjustments, live weighted-average balances and the immutable inventory ledger.</p></div></div>
 <section className="metric-grid"><div className="metric-card"><span>Stock lines</span><strong>{balances?.length??0}</strong></div><div className="metric-card"><span>Total quantity</span><strong>{totalQty.toFixed(2)}</strong></div><div className="metric-card"><span>Inventory value</span><strong>{totalValue.toFixed(2)}</strong></div><div className="metric-card"><span>Ledger rows</span><strong>{tx?.length??0}</strong></div></section>
 <OpeningStockForm products={activeProducts??[]} journals={openingJournals??[]}/>
 <InventoryAdjustmentForm products={activeProducts??[]} accounts={accounts??[]} canPost={canAdjust} action={postInventoryAdjustment}/>
 <section className="panel"><div className="panel-heading"><div><h2>Current balances</h2><p>Purchases, sales, opening stock and adjustments update these balances atomically.</p></div></div>{error?<DataTableEmpty title="Unable to load inventory" description={error.message}/>:balances?.length?<DataTable minWidth={900}><thead><tr><th>Product</th><th>Quantity</th><th>Average cost</th><th>Inventory value</th><th>Updated</th></tr></thead><tbody>{balances.map(x=><tr key={x.id}><td>{product(x.product_id)?.product_code} · {product(x.product_id)?.name}</td><td className="numeric">{Number(x.quantity).toFixed(2)}</td><td className="numeric">{Number(x.average_cost).toFixed(4)}</td><td className="numeric">{Number(x.inventory_value).toFixed(2)}</td><td>{new Date(x.updated_at).toLocaleDateString("en-BD")}</td></tr>)}</tbody></DataTable>:<DataTableEmpty title="No inventory balances" description="Post opening stock or a purchase to receive stock."/>}</section>
 <section className="panel"><div className="panel-heading"><div><h2>Immutable inventory ledger</h2><p>Source movements generated by the database posting workflows.</p></div></div>{tx?.length?<DataTable minWidth={1200}><thead><tr><th>Number</th><th>Date</th><th>Product</th><th>Type</th><th>Direction</th><th>Qty</th><th>Unit cost</th><th>Total</th><th>WAC after</th><th>Reference</th></tr></thead><tbody>{tx.map(x=><tr key={x.id}><td>{x.transaction_number}</td><td>{x.transaction_date}</td><td>{product(x.product_id)?.product_code}</td><td>{x.transaction_type}</td><td>{x.direction}</td><td className="numeric">{Number(x.quantity).toFixed(2)}</td><td className="numeric">{Number(x.unit_cost).toFixed(4)}</td><td className="numeric">{Number(x.total_value).toFixed(2)}</td><td className="numeric">{Number(x.average_cost_after).toFixed(4)}</td><td>{x.reference_type}</td></tr>)}</tbody></DataTable>:<DataTableEmpty title="No inventory transactions" description="Transactions appear after operational posting."/>}</section>
 </div></ErpPageShell>;
}
