import { ErpPageShell } from "@/components/erp-page-shell";
import { ConfigurationManager } from "@/components/configuration-manager";
import { getCurrentOrganization } from "@/lib/supabase/organization";
import { createClient } from "@/lib/supabase/server";
import { saveContact, toggleContact } from "@/app/erp/actions";

export default async function ContactsPage({ searchParams }: { searchParams: Promise<{ edit?: string }> }) {
  const org=await getCurrentOrganization(), supabase=await createClient(), params=await searchParams;
  const {data:rows}=await supabase.from("contacts").select("id,contact_number,name,phone,email,address,is_active,created_at").eq("organization_id",org.id).order("contact_number");
  const editing = params.edit ? (await supabase.from("contacts").select("id,contact_number,name,phone,email,address,is_active").eq("organization_id",org.id).eq("id",params.edit).maybeSingle()).data : undefined;
  const fields=[
    {name:"contact_number",label:"Contact number",placeholder:"Leave blank to use the database sequence"},
    {name:"name",label:"Name",required:true},{name:"phone",label:"Phone"},{name:"email",label:"Email"},{name:"address",label:"Address"},
    {name:"is_active",label:"Active",type:"checkbox" as const},
  ];
  return <ErpPageShell><div className="contacts-page"><div className="page-heading"><div><p className="eyebrow">Masters</p><h1>Contacts</h1><p>One unified contact master is shared by purchasing, sales, expenses and payments.</p></div></div><ConfigurationManager title="Contact" description="Contact numbers are generated by the existing database trigger when omitted." action={saveContact} toggleAction={toggleContact} fields={fields} rows={rows??[]} editingRow={editing} editHref="/contacts" newHref="/contacts" emptyText="No contacts have been configured yet." /></div></ErpPageShell>;
}