import { ErpPageShell } from "@/components/erp-page-shell";
import { ConfigurationManager } from "@/components/configuration-manager";
import { getCurrentOrganization } from "@/lib/supabase/organization";
import { createClient } from "@/lib/supabase/server";
import { saveProduct, toggleProduct } from "@/app/erp/actions";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ edit?: string }> }) {
  const org=await getCurrentOrganization(), supabase=await createClient(), params=await searchParams;
  const [{data:rows},{data:units},{data:accounts}]=await Promise.all([
    supabase.from("products").select("id,product_code,name,description,unit_id,inventory_account_id,sales_account_id,cogs_account_id,is_active,created_at").eq("organization_id",org.id).order("product_code"),
    supabase.from("units_of_measure").select("id,name").eq("organization_id",org.id).eq("is_active",true).order("name"),
    supabase.from("accounts").select("id,account_code,account_name,account_type").eq("organization_id",org.id).eq("is_active",true).eq("is_postable",true).order("account_code"),
  ]);
  const editing = params.edit ? (await supabase.from("products").select("id,product_code,name,description,unit_id,inventory_account_id,sales_account_id,cogs_account_id,is_active").eq("organization_id",org.id).eq("id",params.edit).maybeSingle()).data : undefined;
  const accountLabels = new Map((accounts ?? []).map(x => [x.id, x.account_code + " · " + x.account_name]));
  const unitLabels = new Map((units ?? []).map(x => [x.id, x.name]));
  const tableRows = (rows ?? []).map(row => ({
    ...row,
    unit_display: unitLabels.get(row.unit_id) ?? "Unknown unit",
    inventory_account_display: accountLabels.get(row.inventory_account_id) ?? "Unknown account",
    sales_account_display: accountLabels.get(row.sales_account_id) ?? "Unknown account",
    cogs_account_display: accountLabels.get(row.cogs_account_id) ?? "Unknown account",
  }));
  const fields=[
    {name:"product_code",label:"Product code",placeholder:"Leave blank to use the database sequence"},
    {name:"name",label:"Name",required:true},
    {name:"description",label:"Description"},
    {name:"unit_id",label:"Unit",displayKey:"unit_display",type:"select" as const,required:true,options:(units??[]).map(x=>({value:x.id,label:x.name}))},
    {name:"inventory_account_id",label:"Inventory account",displayKey:"inventory_account_display",type:"select" as const,required:true,options:(accounts??[]).filter(x=>x.account_type==="asset").map(x=>({value:x.id,label:x.account_code+" · "+x.account_name}))},
    {name:"sales_account_id",label:"Sales account",displayKey:"sales_account_display",type:"select" as const,required:true,options:(accounts??[]).filter(x=>x.account_type==="revenue").map(x=>({value:x.id,label:x.account_code+" · "+x.account_name}))},
    {name:"cogs_account_id",label:"COGS account",displayKey:"cogs_account_display",type:"select" as const,required:true,options:(accounts??[]).filter(x=>x.account_type==="expense").map(x=>({value:x.id,label:x.account_code+" · "+x.account_name}))},
    {name:"is_active",label:"Active",type:"checkbox" as const},
  ];
  return <ErpPageShell><div className="products-page"><div className="page-heading"><div><p className="eyebrow">Masters</p><h1>Products</h1><p>Product master records drive inventory valuation and sales accounting.</p></div></div><ConfigurationManager title="Product" description="Product codes are generated by the existing database trigger when omitted." action={saveProduct} toggleAction={toggleProduct} fields={fields} rows={tableRows as Record<string, unknown>[]} editingRow={editing as Record<string, unknown> | undefined} editHref="/products" newHref="/products" emptyText="No products have been configured yet." /></div></ErpPageShell>;
}
