"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { CheckCircle2,XCircle } from "lucide-react";
import { PageHeader,PageSection,StatusBadge } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import { cancelSalesReturn,confirmSalesReturn } from "@/lib/sales/actions";
import { getErrorMessage } from "@/lib/app/errors";
const money=(n:number)=>new Intl.NumberFormat("en-BD",{style:"currency",currency:"BDT",maximumFractionDigits:2}).format(n);
export function ReturnDetail({item}:{item:any}){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function act(kind:"confirm"|"cancel"){setBusy(true);setError("");try{const s=createClient();if(kind==="confirm")await confirmSalesReturn(s,item.id);else await cancelSalesReturn(s,item.id);router.refresh()}catch(c){setError(getErrorMessage(c));setBusy(false)}}return <div className="page"><PageHeader eyebrow="Sales returns" title={item.return_number??"Draft return"} description={"Return against "+(item.sale?.invoice_id??"invoice")} actions={<Link className="button" href="/sales/returns">Back to returns</Link>}/><PageSection title="Return summary" actions={<StatusBadge tone={item.status==="CONFIRMED"?"success":item.status==="CANCELLED"?"danger":"neutral"}>{item.status}</StatusBadge>}><div className="ui-detail-grid"><div><span>Customer</span><strong>{item.customer?.name}</strong></div><div><span>Original invoice</span><strong>{item.sale?.invoice_id}</strong></div><div><span>Return date</span><strong>{item.return_date}</strong></div><div><span>Total</span><strong>{money(Number(item.total_amount))}</strong></div></div></PageSection><PageSection title="Returned items"><div className="ui-table-wrap"><table className="ui-table"><thead><tr><th>#</th><th>Product</th><th>Qty</th><th>Unit price</th><th>Total</th><th>COGS reversal</th></tr></thead><tbody>{item.items.map((i:any)=><tr key={i.id}><td>{i.line_number}</td><td>{i.product?.name}</td><td>{i.quantity}</td><td>{money(Number(i.unit_price))}</td><td>{money(Number(i.line_total))}</td><td>{item.status==="DRAFT"?"Calculated on confirmation":money(Number(i.cogs_total))}</td></tr>)}</tbody></table></div></PageSection>{error?<p className="ui-field-error" role="alert">{error}</p>:null}{item.status==="DRAFT"?<div className="ui-action-bar"><button className="button primary" disabled={busy} onClick={()=>act("confirm")}><CheckCircle2 size={16}/> Confirm & post return</button></div>:item.status==="CONFIRMED"?<div className="ui-action-bar"><button className="button" disabled={busy} onClick={()=>act("cancel")}><XCircle size={16}/> Cancel & reverse</button></div>:null}</div>}
