"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { createSalesReturn } from "@/lib/sales/actions";
import { FormActions,FormField,PageHeader,PageSection,Select } from "@/components/ui";
import { getErrorMessage } from "@/lib/app/errors";

export function ReturnForm({org,userId,accounts,sales}:{org:string;userId:string;accounts:any[];sales:any[]}){const router=useRouter();const today=new Date().toISOString().slice(0,10);const[selected,setSelected]=useState("");const[date,setDate]=useState(today);const[account,setAccount]=useState("");const[qty,setQty]=useState<Record<string,number>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const sale=sales.find(x=>x.id===selected);const items=sale?.items??[];const subtotal=useMemo(()=>items.reduce((n:any,i:any)=>n+(Number(qty[i.id])||0)*Number(i.unit_price),0),[items,qty]);
function selectSale(v:string){setSelected(v);setQty({});const s=sales.find(x=>x.id===v);if(s&&!account)setAccount(accounts[0]?.id??"")}
async function submit(e:React.FormEvent){e.preventDefault();setError("");if(!sale||!account)return setError("Select a sale and receivable account.");const chosen=items.filter((i:any)=>(qty[i.id]||0)>0);if(!chosen.length)return setError("Enter a return quantity for at least one item.");const invalid=chosen.some((i:any)=>(qty[i.id]||0)>Number(i.quantity));if(invalid)return setError("Return quantity cannot exceed the sold quantity on a line.");setBusy(true);try{const ret=await createSalesReturn(createClient(),org,userId,{sales_id:sale.id,customer_id:sale.customer_id,return_date:date,receivable_account_id:account,items:chosen.map((i:any)=>({sales_item_id:i.id,product_id:i.product_id,quantity:Number(qty[i.id]),unit_price:Number(i.unit_price)}))});router.push("/sales/returns/"+ret.id);router.refresh()}catch(c){setError(getErrorMessage(c));setBusy(false)}}
return <div className="page"><PageHeader eyebrow="Sales returns" title="New sales return" description="Create a draft return against a confirmed invoice." actions={<Link className="button" href="/sales/returns">Returns</Link>}/><PageSection title="Return details"><form className="ui-form-grid" onSubmit={submit}><FormField label="Original invoice" required><Select value={selected} onChange={e=>selectSale(e.target.value)}><option value="">Select confirmed invoice</option>{sales.map(s=><option key={s.id} value={s.id}>{s.invoice_id} — {s.customer?.name} — {s.invoice_date}</option>)}</Select></FormField><FormField label="Return date" required><input className="ui-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></FormField><FormField label="Receivable account" required><Select value={account} onChange={e=>setAccount(e.target.value)}><option value="">Select asset account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.account_code} — {a.account_name}</option>)}</Select></FormField>{sale?<div className="ui-table-wrap"><table className="ui-table"><thead><tr><th>Product</th><th>Sold</th><th>Unit price</th><th>Return qty</th><th>Total</th></tr></thead><tbody>{items.map((i:any)=><tr key={i.id}><td>{i.product?.name}</td><td>{i.quantity}</td><td>{Number(i.unit_price).toFixed(2)}</td><td><input className="ui-input" type="number" min="0" max={i.quantity} step="0.0001" value={qty[i.id]??0} onChange={e=>setQty(a=>({...a,[i.id]:Number(e.target.value)}))}/></td><td>{((qty[i.id]||0)*Number(i.unit_price)).toFixed(2)}</td></tr>)}</tbody></table></div>:null}<div className="content-card"><strong>Return total: {subtotal.toFixed(2)}</strong></div>{error?<p className="ui-field-error" role="alert">{error}</p>:null}<FormActions><Link className="button" href="/sales/returns">Cancel</Link><button className="button primary" disabled={busy}>{busy?"Saving…":"Create draft return"}</button></FormActions></form></PageSection></div>}
