/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { CheckCircle2, XCircle } from "lucide-react";
import { PageHeader, PageSection, StatusBadge } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import { cancelSale, confirmSale } from "@/lib/sales/actions";
import { getErrorMessage } from "@/lib/app/errors";

const money=(n:number)=>new Intl.NumberFormat("en-BD",{style:"currency",currency:"BDT",maximumFractionDigits:2}).format(n);
export function SaleDetail({sale}:{sale:any}){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");
async function act(kind:"confirm"|"cancel"){setBusy(true);setError("");try{const s=createClient();if(kind==="confirm")await confirmSale(s,sale.id);else await cancelSale(s,sale.id);router.refresh()}catch(c){setError(getErrorMessage(c));setBusy(false)}}
return <div className="page"><PageHeader eyebrow="Sales" title={sale.invoice_id??"Draft invoice"} description={sale.customer?.name??"Sales document"} actions={<Link className="button" href="/sales/invoices">Back to invoices</Link>}/><PageSection title="Invoice summary" actions={<StatusBadge tone={sale.status==="CONFIRMED"?"success":sale.status==="CANCELLED"?"danger":"neutral"}>{sale.status}</StatusBadge>}><div className="ui-detail-grid"><div><span>Customer</span><strong>{sale.customer?.id?<Link href={"/contacts/"+sale.customer.id}>{sale.customer.name}</Link>:sale.customer?.name}</strong></div><div><span>Date</span><strong>{sale.invoice_date}</strong></div><div><span>Receivable</span><strong>{sale.account?.account_code} — {sale.account?.account_name}</strong></div><div><span>Subtotal</span><strong>{money(Number(sale.subtotal))}</strong></div><div><span>Discount</span><strong>{money(Number(sale.discount_amount))}</strong></div><div><span>Total</span><strong>{money(Number(sale.total_amount))}</strong></div></div></PageSection><PageSection title="Items"><div className="ui-table-wrap"><table className="ui-table"><thead><tr><th>#</th><th>Product</th><th>Qty</th><th>Unit price</th><th>Total</th><th>COGS</th></tr></thead><tbody>{sale.items.map((i:any)=><tr key={i.id}><td>{i.line_number}</td><td>{i.product?.id?<Link href={"/products/"+i.product.id}>{i.product.name}</Link>:i.product?.name??"—"}</td><td>{i.quantity}</td><td>{money(Number(i.unit_price))}</td><td>{money(Number(i.line_total))}</td><td>{sale.status==="DRAFT"?"Calculated on confirmation":money(Number(i.cogs_total))}</td></tr>)}</tbody></table></div></PageSection>{error?<p className="ui-field-error" role="alert">{error}</p>:null}{sale.status==="DRAFT"?<div className="ui-action-bar"><button className="button primary" disabled={busy} onClick={()=>act("confirm")}><CheckCircle2 size={16}/> Confirm & post</button></div>:sale.status==="CONFIRMED"?<div className="ui-action-bar"><button className="button" disabled={busy} onClick={()=>act("cancel")}><XCircle size={16}/> Cancel & reverse</button></div>:null}</div>}
