import { ErpPageShell } from "@/components/erp-page-shell";
import { PageHeader } from "@/components/page-header";
import { DataTable, DataTableEmpty } from "@/components/data-table";
import { ActionForm } from "@/components/action-form";
import { getCurrentOrganization } from "@/lib/supabase/organization";
import { createClient } from "@/lib/supabase/server";
import { updateOrganizationUser } from "@/app/erp/actions";

export default async function UsersSettingsPage() {
  const organization=await getCurrentOrganization(),supabase=await createClient();
  const {data,error}=await supabase.from("organization_users").select("id,user_id,role,is_active,created_at").eq("organization_id",organization.id).order("created_at");
  return <ErpPageShell><div className="settings-page"><PageHeader eyebrow="System administration" title="Users & Roles" description="Manage organization membership roles using the existing organization_users table." actions={<a className="secondary-button compact" href="/settings">Back</a>}/><section className="panel"><div className="panel-heading"><div><h2>Organization members</h2><p>{data?.length??0} membership records</p></div></div>{error?<DataTableEmpty title="Unable to load members" description={error.message}/>:data?.length?<DataTable minWidth={900} ariaLabel="Organization members"><thead><tr><th>User ID</th><th>Role</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{data.map(row=><tr key={row.id}><td><code>{row.user_id}</code></td><td><ActionForm action={updateOrganizationUser} submitLabel="Save"><input type="hidden" name="id" value={row.id}/><select name="role" defaultValue={row.role}><option value="owner">Owner</option><option value="admin">Admin</option><option value="manager">Manager</option><option value="staff">Staff</option></select><select name="is_active" defaultValue={row.is_active?"true":"false"}><option value="true">Active</option><option value="false">Inactive</option></select></ActionForm></td><td><span className={row.is_active?"status-pill active":"status-pill"}>{row.is_active?"Active":"Inactive"}</span></td><td>{new Intl.DateTimeFormat("en-BD",{dateStyle:"medium"}).format(new Date(row.created_at))}</td><td>RLS enforces owner/admin write access and preserves the last active owner.</td></tr>)}</tbody></DataTable>:<DataTableEmpty title="No organization members" description="No membership records were returned for the current organization."/>}</section></div></ErpPageShell>;
}